[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'Shougo/deoplete.nvim'

[[plugins]]
repo = 'benekastah/neomake'

[[plugins]]
repo =  'w0ng/vim-hybrid'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'plasticboy/vim-markdown'

[[plugins]]
repo = 'tpope/vim-fugitive'
